swagger: '2.0'
info:
  title: serverless-felix
  description: API Gateway for serverless-felix
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /discord:
    post:
      summary: Discord interactions proxy
      operationId: discordPost
      x-google-backend:
        address: https://europe-west1-serverless-felix-dev.cloudfunctions.net/discordProxy
        path_translation: CONSTANT_ADDRESS
        jwt_audience: https://europe-west1-serverless-felix-dev.cloudfunctions.net/discordProxy
      responses:
        '200':
          description: OK
  /web:
    get:
      summary: Web proxy
      operationId: webGet
      x-google-backend:
        address: https://europe-west1-serverless-felix-dev.cloudfunctions.net/webProxy
        path_translation: CONSTANT_ADDRESS
        jwt_audience: https://europe-west1-serverless-felix-dev.cloudfunctions.net/webProxy
      responses:
        '200':
          description: OK
    post:
      summary: Web proxy
      operationId: webPost
      x-google-backend:
        address: https://europe-west1-serverless-felix-dev.cloudfunctions.net/webProxy
        path_translation: CONSTANT_ADDRESS
        jwt_audience: https://europe-west1-serverless-felix-dev.cloudfunctions.net/webProxy
      responses:
        '200':
          description: OK
  /oauth:
    get:
      summary: OAuth proxy
      operationId: oauthGet
      x-google-backend:
        address: https://europe-west1-serverless-felix-dev.cloudfunctions.net/oauthProxy
        path_translation: CONSTANT_ADDRESS
        jwt_audience: https://europe-west1-serverless-felix-dev.cloudfunctions.net/oauthProxy
      responses:
        '200':
          description: OK
    post:
      summary: OAuth proxy
      operationId: oauthPost
      x-google-backend:
        address: https://europe-west1-serverless-felix-dev.cloudfunctions.net/oauthProxy
        path_translation: CONSTANT_ADDRESS
        jwt_audience: https://europe-west1-serverless-felix-dev.cloudfunctions.net/oauthProxy
      responses:
        '200':
          description: OK
