name: Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Set GCP Keyfile Path
        run: echo "GCP_KEYFILE_PATH=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: npm run deploy:dev

      - name: Deploy API Gateway (Dev)
        if: github.ref == 'refs/heads/dev'
        run: npm run deploy:dev:gateway

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/main'
        run: npm run deploy:prd

      - name: Deploy API Gateway (Prod)
        if: github.ref == 'refs/heads/main'
        run: npm run deploy:prd:gateway
